### ISSUE TITLE
[JOSS] Write up

### ISSUE THREAD

**Issue by HaoZeke** [gbertoldo/DEPP#2]
Hi, as part of https://github.com/openjournals/joss-reviews/issues/1701, I would prefer if some more of the algorithms could be presented in the JOSS paper. I notice that the `depp_theory.pdf` file has a much better explanation of the overall flow. Could the `.md` file be made to be closer to it?

**Comment by gbertoldo** [comment]
Hi, @HaoZeke. We reproduced depp_theory.pdf in JOSS paper.
