### ISSUE TITLE
[JOSS] Test-suite

### ISSUE THREAD

**Issue by HaoZeke** [gbertoldo/DEPP#3]
The examples are nice, but the `README.md` needs to be clearer about running tests. Actually, though not crucial, it would be nice to have a set of automated tests.

https://github.com/openjournals/joss-reviews/issues/1701

**Comment by gbertoldo** [comment]
I added a Bash script autoCheck.sh in the root of repository. This script checks the compilation of the source code and checks the execution of an example. I also updated the wiki page with instructions on how to used autoCheck.sh (see https://github.com/gbertoldo/DEPP/wiki#how-to-install-depp)

**Comment by HaoZeke** [comment]
There are grammatical issues with the wiki at the moment, also perhaps the test-suite should have its own heading.

**Comment by HaoZeke** [comment]
It would be best to give a list of the dependencies required along with the version which shipped with the linux distro at the time.

**Comment by gbertoldo** [comment]
Hi, @HaoZeke, I added headers to bash scripts. I also put the version of compilers into autoCheck.sh. We will review wiki soon.

**Comment by HaoZeke** [comment]
Thanks! Other than that everything seems to be in order, so as soon as the wiki is updated we're good to go.

**Comment by gbertoldo** [comment]
Hi, @HaoZeke, I updated the wiki. If you find any problem, let me know.
