### ISSUE TITLE
[JOSS] documentation

### ISSUE THREAD

**Issue by dham** [gbertoldo/DEPP#5]
Part of https://github.com/openjournals/joss-reviews/issues/1701

The documentation seems a long way short of what would be needed by a new user. There doesn't really seem to be a manual, just two worked examples. There is also an automatically generated class documentation page, but this seems totally opaque. It's not at all clear what benefit a user would gain from attempting to read this.

The first worked example states "In general, inputs are self-explanatory." This is not true for me at least. How does a user know which options are available? Which values are legal for these options? What is their effect? 

What is the required interface of an external function? What are the constraints on its semantics? For example what if the external function itself expects to run in parallel, how are communicators handled or shared?

**Comment by gbertoldo** [comment]
Hello, @dham,

Thank you for your contributions.

There was a document in the repository describing the theory behind DEPP. I moved the content of this document to JOSS paper after a suggestion of @HaoZeke. I believe that the paper is fundamental to understand how to use DEPP. So, I will provide a link to the JOSS paper in the wiki.  

The automatically generated class documentation page is intended for more advanced users, who want to modify the source code. I do not think it must be changed.

We will provide a more detailed explanation about input parameters and interfacing on the wiki page. We will also answer the question about the external function running in parallel.

Let me know if these modifications are satisfactory.

**Comment by dham** [comment]
Thanks, I saw the change you made to the paper at the other reviewer's request. I think the key distinction that I am raising here is the lack of high quality user documentation, which is a different problem from the explanation of the mathematics underpinning the tool. In essence the issue is that there isn't really a manual in the sense that a user of software would expect. I think that my specific questions above are particular symptoms of this. The more generic question that a manual would need to answer is, how would a user with no connection to the authors know what all of the capabilities of the software are, and how to practically access those capabilities?

I also have some concerns about the software engineering of DEPP itself. I was waiting to confirm with the editor, @meg-simula, whether these were in scope for a JOSS review. Having learned that they are, I will open more issues on these subjects.

**Comment by gbertoldo** [comment]
Ok, I understand. We want to improve the software quality and your contributions are welcome. Could you give me examples of what is considered a high-quality user documentation?

**Comment by dham** [comment]
I think a very good example is the documentation for triangle, which is a 2D mesh generator. https://www.cs.cmu.edu/~quake/triangle.html

Even though it's a different area of computational science, I think it's similar in scope to DEPP in that it's a single executable, compiled programme with something like the same number of optional parameters. The web page is a bit old-fashioned in style, but the content is very good. As a new user, I can easily find everything that triangle can do, and what options I would use to make triangle do it.

**Comment by gbertoldo** [comment]
Hi, @dham and @HaoZeke, I think this issue is solved. We updated the wiki page and JOSS paper.  

We describe here https://github.com/gbertoldo/DEPP/wiki/How-to-install-DEPP-on-Linux how to install DEPP on six Linux distros, how to check DEPP installation and how to perform automatic code verification.
This page https://github.com/gbertoldo/DEPP/wiki/How-to-use-DEPP describes how to run DEPP using command-line terminal, how to perform DEPP interfacing with the external fitness calculator, explains how to set up the configuration file, presents the meaning of all parameters, their types and available options and, finally, how to use DEPP by examples.

**Comment by dham** [comment]
I agree. This is very much better.
