### ISSUE TITLE
[JOSS] DOIs Missing

### ISSUE THREAD

**Issue by HaoZeke** [gbertoldo/DEPP#8]
Part of https://github.com/openjournals/joss-reviews/issues/1701

@whedon [seems to feel ](https://github.com/openjournals/joss-reviews/issues/1701#issuecomment-562816864)that some of the DOIs are missing.

**Comment by gbertoldo** [comment]
Hi, @HaoZeke!

@whedon found a paper that has the same title as a book we cited in JOSS paper. (Response Surface Methodology: Process and Product Optimization Using Designed Experiments). This book has no DOI.
